import { fotosSeed } from "./fotos-microcuenca";
import type { JaStoreState } from "./zod";

function conFotos<T>(rows: T[], offset = 0): Array<T & { fotos: string[] }> {
  return rows.map((row, i) => ({ ...row, fotos: fotosSeed(i + offset) }));
}

export function seedState(): JaStoreState {
  return {
    incidentes: conFotos([
      {
        id: "inc-001",
        folio: "JA-MUYU-20260312-A1C3",
        fecha: "2026-03-12",
        microcuenca: "Muyurco",
        municipio: "Camotán",
        criticidad: "alerta_amarilla",
        tipologia: "Déficit por canículas prolongadas",
        descripcion:
          "Reducción del caudal de nacimientos en caseríos de Muyurco durante la canícula. El Comité Comunitario de Agua reporta racionamiento vespertino.",
        poblacion: { hombres: 86, mujeres: 112, juventudes: 74, pueblo_maya_chorti: 148 },
        confidencial: true,
        id_anonimo: "JA-CONF-4K9M2P",
        derivacion: "Comités Comunitarios de Agua",
        asignado_usuario_id: null,
        asignado_a: "Comité de Agua Muyurco — OMAS Camotán",
        created_at: "2026-03-12T14:20:00.000Z",
        updated_at: null,
      },
      {
        id: "inc-002",
        folio: "JA-TACO-20260402-B7D1",
        fecha: "2026-04-02",
        microcuenca: "Río Taco",
        municipio: "Jocotán",
        criticidad: "latente",
        tipologia: "Contaminación por desechos y aguas residuales",
        descripcion:
          "Vertido de aguas residuales hacia afluentes del Río Taco. Vecinas de la aldea reportan olores y riesgo sanitario en puntos de lavado.",
        poblacion: { hombres: 54, mujeres: 81, juventudes: 49, pueblo_maya_chorti: 97 },
        confidencial: true,
        id_anonimo: "JA-CONF-8R2N6Q",
        derivacion: "UGAM",
        asignado_usuario_id: null,
        asignado_a: "UGAM Jocotán",
        created_at: "2026-04-02T09:05:00.000Z",
        updated_at: null,
      },
      {
        id: "inc-003",
        folio: "JA-GUAR-20260218-C3E8",
        fecha: "2026-02-18",
        microcuenca: "Guaraquiche",
        municipio: "Olopa",
        criticidad: "manifiesto",
        tipologia: "Degradación de zona de recarga",
        descripcion:
          "Tala en ladera de recarga de Guaraquiche. La asamblea comunitaria solicitó intervención de MARN y mediación con el Comité de Microcuenca.",
        poblacion: { hombres: 63, mujeres: 71, juventudes: 38, pueblo_maya_chorti: 109 },
        confidencial: false,
        id_anonimo: null,
        derivacion: "OMAS",
        asignado_usuario_id: null,
        asignado_a: "OMAS Olopa / MARN Delegación Chiquimula",
        created_at: "2026-02-18T16:40:00.000Z",
        updated_at: null,
      },
      {
        id: "inc-004",
        folio: "JA-CAYU-20260521-D5F2",
        fecha: "2026-05-21",
        microcuenca: "Río Cayur",
        municipio: "San Juan Ermita",
        criticidad: "alerta_verde",
        tipologia: "Actividades extractivas o productivas sin control",
        descripcion:
          "Apertura de banco de materiales cerca del cauce del Río Cayur. Se activa seguimiento preventivo con UGAM y COCODE.",
        poblacion: { hombres: 41, mujeres: 39, juventudes: 28, pueblo_maya_chorti: 52 },
        confidencial: false,
        id_anonimo: null,
        derivacion: "UGAM",
        asignado_usuario_id: null,
        asignado_a: "UGAM San Juan Ermita",
        created_at: "2026-05-21T11:15:00.000Z",
        updated_at: null,
      },
      {
        id: "inc-005",
        folio: "JA-CARC-20260130-E9A4",
        fecha: "2026-01-30",
        microcuenca: "Quebrada Carcaj",
        municipio: "Chiquimula",
        criticidad: "latente",
        tipologia: "Disputas intermunicipales o comunitarias",
        descripcion:
          "Desacuerdo entre comunidades ribereñas de Quebrada Carcaj por turnos de riego en época seca. Se convoca mesa preparatoria.",
        poblacion: { hombres: 97, mujeres: 104, juventudes: 66, pueblo_maya_chorti: 41 },
        confidencial: false,
        id_anonimo: null,
        derivacion: "OMAS",
        asignado_usuario_id: null,
        asignado_a: "OMAS Chiquimula",
        created_at: "2026-01-30T08:50:00.000Z",
        updated_at: null,
      },
      {
        id: "inc-006",
        folio: "JA-MUYU-20260418-F2B8",
        fecha: "2026-04-18",
        microcuenca: "Muyurco",
        municipio: "Camotán",
        criticidad: "latente",
        tipologia: "Degradación de zona de recarga",
        descripcion:
          "Quema agrícola en ladera de recarga de Muyurco. El Comité de Microcuenca pidió inspección conjunta con OMAS.",
        poblacion: { hombres: 48, mujeres: 61, juventudes: 33, pueblo_maya_chorti: 72 },
        confidencial: false,
        id_anonimo: null,
        derivacion: "OMAS",
        asignado_usuario_id: null,
        asignado_a: "OMAS Camotán",
        created_at: "2026-04-18T10:12:00.000Z",
        updated_at: null,
      },
      {
        id: "inc-007",
        folio: "JA-MUYU-20260503-G4C1",
        fecha: "2026-05-03",
        microcuenca: "Muyurco",
        municipio: "Camotán",
        criticidad: "manifiesto",
        tipologia: "Disputas intermunicipales o comunitarias",
        descripcion:
          "Conflicto por toma de agua entre dos caseríos de Muyurco. Se registran cortes no autorizados de tubería.",
        poblacion: { hombres: 72, mujeres: 88, juventudes: 51, pueblo_maya_chorti: 119 },
        confidencial: true,
        id_anonimo: "JA-CONF-2H7L9T",
        derivacion: "Comités Comunitarios de Agua",
        asignado_usuario_id: null,
        asignado_a: "Comité de Agua Muyurco / Alcaldía Camotán",
        created_at: "2026-05-03T15:40:00.000Z",
        updated_at: null,
      },
      {
        id: "inc-008",
        folio: "JA-TACO-20260322-H8D3",
        fecha: "2026-03-22",
        microcuenca: "Río Taco",
        municipio: "Jocotán",
        criticidad: "alerta_amarilla",
        tipologia: "Déficit por canículas prolongadas",
        descripcion:
          "Pozo comunitario de Río Taco con nivel crítico. Juventudes de cuenca reportan acarreo de más de 40 minutos.",
        poblacion: { hombres: 39, mujeres: 58, juventudes: 44, pueblo_maya_chorti: 67 },
        confidencial: false,
        id_anonimo: null,
        derivacion: "OMAS",
        asignado_usuario_id: null,
        asignado_a: "OMAS Jocotán",
        created_at: "2026-03-22T08:20:00.000Z",
        updated_at: null,
      },
      {
        id: "inc-009",
        folio: "JA-TACO-20260514-J1E6",
        fecha: "2026-05-14",
        microcuenca: "Río Taco",
        municipio: "Jocotán",
        criticidad: "manifiesto",
        tipologia: "Contaminación por desechos y aguas residuales",
        descripcion:
          "Brotes gastrointestinales asociados a un afluente del Río Taco. La Red de Mujeres HOSAGUA solicitó reserva de identidad de denunciantes.",
        poblacion: { hombres: 61, mujeres: 94, juventudes: 58, pueblo_maya_chorti: 88 },
        confidencial: true,
        id_anonimo: "JA-CONF-6P3W1K",
        derivacion: "UGAM",
        asignado_usuario_id: null,
        asignado_a: "UGAM Jocotán / Centro de Salud",
        created_at: "2026-05-14T12:05:00.000Z",
        updated_at: null,
      },
      {
        id: "inc-010",
        folio: "JA-GUAR-20260408-K5F2",
        fecha: "2026-04-08",
        microcuenca: "Guaraquiche",
        municipio: "Olopa",
        criticidad: "alerta_verde",
        tipologia: "Actividades extractivas o productivas sin control",
        descripcion:
          "Ampliación de parcela hacia nacimiento en Guaraquiche. Se activa alerta preventiva con el Comité de Microcuenca.",
        poblacion: { hombres: 27, mujeres: 31, juventudes: 19, pueblo_maya_chorti: 41 },
        confidencial: false,
        id_anonimo: null,
        derivacion: "UGAM",
        asignado_usuario_id: null,
        asignado_a: "UGAM Olopa",
        created_at: "2026-04-08T09:30:00.000Z",
        updated_at: null,
      },
      {
        id: "inc-011",
        folio: "JA-GUAR-20260602-L9A7",
        fecha: "2026-06-02",
        microcuenca: "Guaraquiche",
        municipio: "Olopa",
        criticidad: "latente",
        tipologia: "Déficit por canículas prolongadas",
        descripcion:
          "Secado parcial de un nacimiento usado por tres comunidades de Guaraquiche. Se programa medición semanal de caudal.",
        poblacion: { hombres: 55, mujeres: 64, juventudes: 42, pueblo_maya_chorti: 90 },
        confidencial: false,
        id_anonimo: null,
        derivacion: "Comités Comunitarios de Agua",
        asignado_usuario_id: null,
        asignado_a: "Comité de Microcuenca Guaraquiche",
        created_at: "2026-06-02T11:45:00.000Z",
        updated_at: null,
      },
      {
        id: "inc-012",
        folio: "JA-CAYU-20260305-M3B4",
        fecha: "2026-03-05",
        microcuenca: "Río Cayur",
        municipio: "San Juan Ermita",
        criticidad: "alerta_amarilla",
        tipologia: "Contaminación por desechos y aguas residuales",
        descripcion:
          "Arrastre de agroquímicos hacia el Río Cayur tras lluvias. El COCODE pidió muestreo de calidad del agua.",
        poblacion: { hombres: 34, mujeres: 41, juventudes: 22, pueblo_maya_chorti: 48 },
        confidencial: false,
        id_anonimo: null,
        derivacion: "UGAM",
        asignado_usuario_id: null,
        asignado_a: "UGAM San Juan Ermita",
        created_at: "2026-03-05T16:10:00.000Z",
        updated_at: null,
      },
      {
        id: "inc-013",
        folio: "JA-CAYU-20260611-N7C9",
        fecha: "2026-06-11",
        microcuenca: "Río Cayur",
        municipio: "San Juan Ermita",
        criticidad: "latente",
        tipologia: "Disputas intermunicipales o comunitarias",
        descripcion:
          "Tensión por linderos de servidumbre de paso hacia un nacimiento en Río Cayur. Se solicita gestor de diálogo.",
        poblacion: { hombres: 29, mujeres: 26, juventudes: 18, pueblo_maya_chorti: 37 },
        confidencial: true,
        id_anonimo: "JA-CONF-9Q4V8M",
        derivacion: "OMAS",
        asignado_usuario_id: null,
        asignado_a: "OMAS San Juan Ermita",
        created_at: "2026-06-11T14:00:00.000Z",
        updated_at: null,
      },
      {
        id: "inc-014",
        folio: "JA-CARC-20260425-P2D5",
        fecha: "2026-04-25",
        microcuenca: "Quebrada Carcaj",
        municipio: "Chiquimula",
        criticidad: "alerta_verde",
        tipologia: "Déficit por canículas prolongadas",
        descripcion:
          "Bajada temprana de caudal en Quebrada Carcaj. Redes juveniles instalaron puntos de observación.",
        poblacion: { hombres: 44, mujeres: 49, juventudes: 38, pueblo_maya_chorti: 21 },
        confidencial: false,
        id_anonimo: null,
        derivacion: "OMAS",
        asignado_usuario_id: null,
        asignado_a: "OMAS Chiquimula",
        created_at: "2026-04-25T07:55:00.000Z",
        updated_at: null,
      },
      {
        id: "inc-015",
        folio: "JA-CARC-20260529-Q8E1",
        fecha: "2026-05-29",
        microcuenca: "Quebrada Carcaj",
        municipio: "Chiquimula",
        criticidad: "manifiesto",
        tipologia: "Actividades extractivas o productivas sin control",
        descripcion:
          "Extracción de arena en lecho de Quebrada Carcaj. Vecinos reportan socavación y riesgo a tomas de riego.",
        poblacion: { hombres: 81, mujeres: 76, juventudes: 45, pueblo_maya_chorti: 33 },
        confidencial: false,
        id_anonimo: null,
        derivacion: "UGAM",
        asignado_usuario_id: null,
        asignado_a: "UGAM Chiquimula / MARN",
        created_at: "2026-05-29T13:25:00.000Z",
        updated_at: null,
      },
      {
        id: "inc-016",
        folio: "JA-TACO-20260620-R4F7",
        fecha: "2026-06-20",
        microcuenca: "Río Taco",
        municipio: "Jocotán",
        criticidad: "alerta_verde",
        tipologia: "Degradación de zona de recarga",
        descripcion:
          "Apertura de camino vecinal sobre zona de recarga del Río Taco. Se documenta para seguimiento técnico.",
        poblacion: { hombres: 22, mujeres: 19, juventudes: 15, pueblo_maya_chorti: 28 },
        confidencial: false,
        id_anonimo: null,
        derivacion: "UGAM",
        asignado_usuario_id: null,
        asignado_a: "UGAM Jocotán",
        created_at: "2026-06-20T09:10:00.000Z",
        updated_at: null,
      },
      {
        id: "inc-017",
        folio: "JA-MUYU-20260628-S6G2",
        fecha: "2026-06-28",
        microcuenca: "Muyurco",
        municipio: "Camotán",
        criticidad: "alerta_amarilla",
        tipologia: "Contaminación por desechos y aguas residuales",
        descripcion:
          "Acumulación de desechos sólidos en cauce intermitente de Muyurco previo a la temporada de lluvias.",
        poblacion: { hombres: 36, mujeres: 47, juventudes: 29, pueblo_maya_chorti: 58 },
        confidencial: false,
        id_anonimo: null,
        derivacion: "Comités Comunitarios de Agua",
        asignado_usuario_id: null,
        asignado_a: "Comité de Agua Muyurco",
        created_at: "2026-06-28T17:05:00.000Z",
        updated_at: null,
      },
    ], 0),
    sesiones: conFotos([
      {
        id: "ses-001",
        titulo: "Mesa de caudal y racionamiento — Muyurco",
        fecha: "2026-03-28",
        microcuenca: "Muyurco",
        municipio: "Camotán",
        fase: "intercambio",
        incidente_id: "inc-001",
        notas: "Intercambio entre Comité de Agua, OMAS y Red de Mujeres HOSAGUA.",
        created_at: "2026-03-20T10:00:00.000Z",
        updated_at: null,
      },
      {
        id: "ses-002",
        titulo: "Sesión formal de recarga — Guaraquiche",
        fecha: "2026-03-10",
        microcuenca: "Guaraquiche",
        municipio: "Olopa",
        fase: "formal",
        incidente_id: "inc-003",
        notas: "Instalación formal con MARN, Alcaldía de Olopa y Comité de Microcuenca.",
        created_at: "2026-02-25T15:00:00.000Z",
        updated_at: null,
      },
      {
        id: "ses-003",
        titulo: "Preparatoria de turnos de riego — Quebrada Carcaj",
        fecha: "2026-02-14",
        microcuenca: "Quebrada Carcaj",
        municipio: "Chiquimula",
        fase: "preparatoria",
        incidente_id: "inc-005",
        notas: "Mapeo de actores y reglas de palabra con pertinencia cultural.",
        created_at: "2026-02-04T09:30:00.000Z",
        updated_at: null,
      },
    ], 20),
    acuerdos: conFotos([
      {
        id: "acu-001",
        sesion_id: "ses-001",
        incidente_id: "inc-001",
        descripcion: "Calendario comunitario de racionamiento y monitoreo semanal de caudal.",
        institucion_responsable: "Comité Comunitario de Agua",
        fecha_limite: "2026-06-30",
        estado: "en_proceso",
        efectividad: 3,
        medio_verificacion: "Acta comunal Muyurco — lista de asistencia 28/03/2026",
        created_at: "2026-03-28T18:00:00.000Z",
        updated_at: null,
      },
      {
        id: "acu-002",
        sesion_id: "ses-002",
        incidente_id: "inc-003",
        descripcion: "Cierre temporal de tala en ladera de recarga y reforestación de 4 ha.",
        institucion_responsable: "MARN",
        fecha_limite: "2026-05-15",
        estado: "cumplido",
        efectividad: 5,
        medio_verificacion: "Acta de inspección MARN y lista de jornada de reforestación",
        created_at: "2026-03-10T17:20:00.000Z",
        updated_at: null,
      },
      {
        id: "acu-003",
        sesion_id: "ses-002",
        incidente_id: "inc-003",
        descripcion: "Ordenanza municipal de protección de zona de recarga en Guaraquiche.",
        institucion_responsable: "Alcaldía",
        fecha_limite: "2026-04-30",
        estado: "incumplido",
        efectividad: 2,
        medio_verificacion: "Borrador de acuerdo municipal pendiente de sesión de concejo",
        created_at: "2026-03-10T17:25:00.000Z",
        updated_at: null,
      },
      {
        id: "acu-004",
        sesion_id: "ses-003",
        incidente_id: "inc-005",
        descripcion: "Reglamento provisional de turnos de riego entre comunidades ribereñas.",
        institucion_responsable: "COCODE",
        fecha_limite: "2026-07-15",
        estado: "en_proceso",
        efectividad: 3,
        medio_verificacion: "Minuta preparatoria y croquis de tomas",
        created_at: "2026-02-14T13:10:00.000Z",
        updated_at: null,
      },
    ], 30),
    proyectos: conFotos([
      {
        id: "pry-001",
        nombre: "Cosecha de lluvia en caseríos de Muyurco",
        comunidad: "Aldea El Guayabo",
        microcuenca: "Muyurco",
        municipio: "Camotán",
        agencia: "PNUD",
        tipologia: "Cosecha de agua de lluvia",
        avance_fisico: 68,
        presupuesto_total: 420000,
        presupuesto_ejecutado: 286000,
        representatividad_comunitaria: 62,
        impacto_medios_vida: 4,
        innovacion_climatica: 4,
        created_at: "2025-11-02T00:00:00.000Z",
        updated_at: null,
      },
      {
        id: "pry-002",
        nombre: "Protección de nacimientos del Río Taco",
        comunidad: "Aldea Taco",
        microcuenca: "Río Taco",
        municipio: "Jocotán",
        agencia: "FAO",
        tipologia: "Protección de nacimientos",
        avance_fisico: 44,
        presupuesto_total: 310000,
        presupuesto_ejecutado: 128000,
        representatividad_comunitaria: 55,
        impacto_medios_vida: 3,
        innovacion_climatica: 3,
        created_at: "2026-01-15T00:00:00.000Z",
        updated_at: null,
      },
      {
        id: "pry-003",
        nombre: "Micro-riego familiar en Guaraquiche",
        comunidad: "Caserío Las Flores",
        microcuenca: "Guaraquiche",
        municipio: "Olopa",
        agencia: "FAO",
        tipologia: "Sistemas de micro-riego",
        avance_fisico: 81,
        presupuesto_total: 265000,
        presupuesto_ejecutado: 214000,
        representatividad_comunitaria: 71,
        impacto_medios_vida: 5,
        innovacion_climatica: 4,
        created_at: "2025-09-08T00:00:00.000Z",
        updated_at: null,
      },
      {
        id: "pry-004",
        nombre: "Bosque de recarga en Río Cayur",
        comunidad: "Aldea El Rodeo",
        microcuenca: "Río Cayur",
        municipio: "San Juan Ermita",
        agencia: "PNUD",
        tipologia: "Conservación forestal de recarga",
        avance_fisico: 37,
        presupuesto_total: 390000,
        presupuesto_ejecutado: 142000,
        representatividad_comunitaria: 48,
        impacto_medios_vida: 3,
        innovacion_climatica: 5,
        created_at: "2026-02-01T00:00:00.000Z",
        updated_at: null,
      },
    ], 40),
    metodologias: conFotos([
      {
        id: "met-001",
        titulo: "Protocolo de mediación con pertinencia Maya Ch'orti'",
        tipo: "Protocolo de mediación",
        pertinencia: "Pueblo Maya Ch'orti' — palabra circular y respeto a autoridades comunitarias",
        microcuenca: null,
        resumen:
          "Guía para instalar mesas de diálogo en la Cuenca del Río Grande con traducción, tiempos rituales y reserva de identidad.",
      },
      {
        id: "met-002",
        titulo: "Monitoreo comunitario de caudal en canícula",
        tipo: "Guía",
        pertinencia: "Comités de agua y juventudes de microcuenca",
        microcuenca: "Muyurco",
        resumen:
          "Fichas de medición semanal, semáforo de alerta temprana y bitácora para OMAS/UGAM.",
      },
      {
        id: "met-003",
        titulo: "Estudio de caso: recarga de Guaraquiche",
        tipo: "Estudio de caso",
        pertinencia: "Comité de microcuenca y Alcaldía de Olopa",
        microcuenca: "Guaraquiche",
        resumen:
          "Lecciones del acuerdo de reforestación y la ordenanza municipal pendiente en zona de recarga.",
      },
      {
        id: "met-004",
        titulo: "Acción Sin Daño en denuncias hídricas",
        tipo: "Guía",
        pertinencia: "Mujeres, juventudes y defensores ambientales",
        microcuenca: null,
        resumen:
          "Protocolo de anonimización, IDs reservados y canales de derivación a OMAS, UGAM y comités.",
      },
    ], 50),
    organizaciones: conFotos([
      {
        id: "org-001",
        nombre: "Red de Mujeres HOSAGUA",
        tipo: "Red de mujeres",
        municipio: "Jocotán",
        contacto: "Articulación comunitaria — reserva de identidad disponible",
        descripcion: "Liderazgos de mujeres en Gestión de los Recursos Hídricos y vigilancia de calidad del agua.",
        mujeres_liderazgo: 18,
        juventudes_liderazgo: 7,
      },
      {
        id: "org-002",
        nombre: "Pluriversidad Maya Ch'orti'",
        tipo: "Espacio de saberes",
        municipio: "Camotán",
        contacto: "Consejo de mayores y maestras de idioma",
        descripcion: "Intercambio de conocimientos territoriales y protocolos de diálogo con pertinencia cultural.",
        mujeres_liderazgo: 9,
        juventudes_liderazgo: 11,
      },
      {
        id: "org-003",
        nombre: "Instituto Upejkna'r E Ja'",
        tipo: "Instituto de formación",
        municipio: "Olopa",
        contacto: "Equipo pedagógico de cuenca",
        descripcion: "Formación técnica en Gestión de los Recursos Hídricos y pedagogía del agua Ja'.",
        mujeres_liderazgo: 6,
        juventudes_liderazgo: 14,
      },
      {
        id: "org-004",
        nombre: "Redes juveniles de cuenca",
        tipo: "Red juvenil",
        municipio: "Chiquimula",
        contacto: "Enlace intermunicipal de juventudes",
        descripcion: "Monitoreo ciudadano, comunicación comunitaria y veeduría de acuerdos.",
        mujeres_liderazgo: 12,
        juventudes_liderazgo: 22,
      },
      {
        id: "org-005",
        nombre: "Comité de Microcuenca Río Cayur",
        tipo: "Comité de microcuenca",
        municipio: "San Juan Ermita",
        contacto: "Presidencia rotativa del comité",
        descripcion: "Coordinación de nacimientos, recarga y primera respuesta con UGAM.",
        mujeres_liderazgo: 5,
        juventudes_liderazgo: 4,
      },
    ], 60),
    evidencias: conFotos([
      {
        id: "evi-001",
        titulo: "Acta comunal de racionamiento — Muyurco",
        tipo: "Acta comunal",
        etiqueta: "Reservada",
        fecha: "2026-03-28",
        vinculado: "Acuerdo acu-001",
      },
      {
        id: "evi-002",
        titulo: "Lista de asistencia — sesión formal Guaraquiche",
        tipo: "Lista de asistencia",
        etiqueta: "Pública",
        fecha: "2026-03-10",
        vinculado: "Sesión ses-002",
      },
      {
        id: "evi-003",
        titulo: "Informe de inspección de recarga — MARN",
        tipo: "Informe técnico",
        etiqueta: "Reservada",
        fecha: "2026-05-12",
        vinculado: "Acuerdo acu-002",
      },
      {
        id: "evi-004",
        titulo: "Registro anónimo de primera denuncia — Río Taco",
        tipo: "Registro confidencial",
        etiqueta: "Confidencial — Acción Sin Daño",
        fecha: "2026-04-02",
        vinculado: "Incidente JA-CONF-8R2N6Q",
      },
      {
        id: "evi-005",
        titulo: "Ficha de avance físico — micro-riego Las Flores",
        tipo: "Medio de verificación PBF",
        etiqueta: "Pública",
        fecha: "2026-06-18",
        vinculado: "Proyecto pry-003",
      },
    ], 70),
    procesos: [],
  };
}
